<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dbg_bpF' shared service.

return $this->privates['.service_locator.dbg_bpF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Userconnecte' => ['privates', '.errored..service_locator.dbg_bpF.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.dbg_bpF": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repoComp' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'repoProfil' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'Userconnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'encoder' => '?',
    'manager' => '?',
    'repoComp' => 'App\\Repository\\CompteRepository',
    'repoProfil' => 'App\\Repository\\ProfilRepository',
    'validator' => '?',
]);
