<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.json_serialization_visitor' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Visitor/Factory/SerializationVisitorFactory.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Visitor/Factory/JsonSerializationVisitorFactory.php';

$this->privates['jms_serializer.json_serialization_visitor'] = $instance = new \JMS\Serializer\Visitor\Factory\JsonSerializationVisitorFactory();

$instance->setOptions(1024);

return $instance;
