<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UomhiZc' shared service.

return $this->privates['.service_locator.UomhiZc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'user' => ['privates', '.errored..service_locator.UomhiZc.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.UomhiZc": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'userConnecte' => ['privates', '.errored..service_locator.UomhiZc.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.UomhiZc": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'serializer' => '?',
    'user' => 'App\\Entity\\Utilisateur',
    'userConnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
