<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3ke85KT' shared service.

return $this->privates['.service_locator.3ke85KT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repo' => ['privates', 'App\\Repository\\UserCompteActuelRepository', 'getUserCompteActuelRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'user' => ['privates', '.errored..service_locator.3ke85KT.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.3ke85KT": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
], [
    'repo' => 'App\\Repository\\UserCompteActuelRepository',
    'serializer' => '?',
    'user' => 'App\\Entity\\Utilisateur',
]);
