<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fLHhYHo' shared service.

return $this->privates['.service_locator.fLHhYHo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entreprise' => ['privates', '.errored..service_locator.fLHhYHo.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.fLHhYHo": it references class "App\\Entity\\Entreprise" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'entreprise' => 'App\\Entity\\Entreprise',
    'repo' => 'App\\Repository\\UtilisateurRepository',
    'serializer' => '?',
]);
