<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pV4HNdF' shared service.

return $this->privates['.service_locator.pV4HNdF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entreprise' => ['privates', '.errored..service_locator.pV4HNdF.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.pV4HNdF": it references class "App\\Entity\\Entreprise" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'entreprise' => 'App\\Entity\\Entreprise',
    'manager' => '?',
]);
