<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rfN.IFF' shared service.

return $this->privates['.service_locator.rfN.IFF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Userconnecte' => ['privates', '.errored..service_locator.rfN.IFF.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.rfN.IFF": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repoCompte' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'repoUser' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'Userconnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'manager' => '?',
    'repoCompte' => 'App\\Repository\\CompteRepository',
    'repoUser' => 'App\\Repository\\UtilisateurRepository',
]);
