<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JE0vXO5' shared service.

return $this->privates['.service_locator.JE0vXO5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::inscriptionUtilisateur' => ['privates', '.service_locator.gb6KpeQ', 'get_ServiceLocator_Gb6KpeQService.php', true],
    'App\\Controller\\SecurityController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:inscriptionUtilisateur' => ['privates', '.service_locator.gb6KpeQ', 'get_ServiceLocator_Gb6KpeQService.php', true],
    'App\\Controller\\SecurityController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\SecurityController::inscriptionUtilisateur' => '?',
    'App\\Controller\\SecurityController::setViewHandler' => '?',
    'App\\Controller\\SecurityController:inscriptionUtilisateur' => '?',
    'App\\Controller\\SecurityController:setViewHandler' => '?',
]);
