<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5zcue4K' shared service.

return $this->privates['.service_locator.5zcue4K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EntrepriseController::add' => ['privates', '.service_locator.NpJNP1H', 'get_ServiceLocator_NpJNP1HService.php', true],
    'App\\Controller\\EntrepriseController::addCompte' => ['privates', '.service_locator.pV4HNdF', 'get_ServiceLocator_PV4HNdFService.php', true],
    'App\\Controller\\EntrepriseController::bloque' => ['privates', '.service_locator.ut29XRA', 'get_ServiceLocator_Ut29XRAService.php', true],
    'App\\Controller\\EntrepriseController::depot' => ['privates', '.service_locator.vD8Uu7b', 'get_ServiceLocator_VD8Uu7bService.php', true],
    'App\\Controller\\EntrepriseController::lister' => ['privates', '.service_locator.6tT8guL', 'get_ServiceLocator_6tT8guLService.php', true],
    'App\\Controller\\EntrepriseController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController::inscriptionUtilisateur' => ['privates', '.service_locator.5FGfkQK', 'get_ServiceLocator_5FGfkQKService.php', true],
    'App\\Controller\\SecurityController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\EntrepriseController:add' => ['privates', '.service_locator.NpJNP1H', 'get_ServiceLocator_NpJNP1HService.php', true],
    'App\\Controller\\EntrepriseController:addCompte' => ['privates', '.service_locator.pV4HNdF', 'get_ServiceLocator_PV4HNdFService.php', true],
    'App\\Controller\\EntrepriseController:bloque' => ['privates', '.service_locator.ut29XRA', 'get_ServiceLocator_Ut29XRAService.php', true],
    'App\\Controller\\EntrepriseController:depot' => ['privates', '.service_locator.vD8Uu7b', 'get_ServiceLocator_VD8Uu7bService.php', true],
    'App\\Controller\\EntrepriseController:lister' => ['privates', '.service_locator.6tT8guL', 'get_ServiceLocator_6tT8guLService.php', true],
    'App\\Controller\\EntrepriseController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:inscriptionUtilisateur' => ['privates', '.service_locator.5FGfkQK', 'get_ServiceLocator_5FGfkQKService.php', true],
    'App\\Controller\\SecurityController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\EntrepriseController::add' => '?',
    'App\\Controller\\EntrepriseController::addCompte' => '?',
    'App\\Controller\\EntrepriseController::bloque' => '?',
    'App\\Controller\\EntrepriseController::depot' => '?',
    'App\\Controller\\EntrepriseController::lister' => '?',
    'App\\Controller\\EntrepriseController::setViewHandler' => '?',
    'App\\Controller\\SecurityController::inscriptionUtilisateur' => '?',
    'App\\Controller\\SecurityController::setViewHandler' => '?',
    'App\\Controller\\EntrepriseController:add' => '?',
    'App\\Controller\\EntrepriseController:addCompte' => '?',
    'App\\Controller\\EntrepriseController:bloque' => '?',
    'App\\Controller\\EntrepriseController:depot' => '?',
    'App\\Controller\\EntrepriseController:lister' => '?',
    'App\\Controller\\EntrepriseController:setViewHandler' => '?',
    'App\\Controller\\SecurityController:inscriptionUtilisateur' => '?',
    'App\\Controller\\SecurityController:setViewHandler' => '?',
]);
