<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2JXh8BC' shared service.

return $this->privates['.service_locator.2JXh8BC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entreprise' => ['privates', '.errored..service_locator.2JXh8BC.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.2JXh8BC": it references class "App\\Entity\\Entreprise" but no such service exists.'],
], [
    'entreprise' => 'App\\Entity\\Entreprise',
]);
