<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.UomhiZc.App\Entity\Utilisateur' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/User/UserInterface.php';
include_once $this->targetDirs[3].'/src/Entity/Utilisateur.php';

return $this->privates['.errored..service_locator.UomhiZc.App\\Entity\\Utilisateur'] = new \App\Entity\Utilisateur();
