<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer.form_error_handler.inner' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Handler/FormErrorHandler.php';

return $this->privates['fos_rest.serializer.form_error_handler.inner'] = new \JMS\Serializer\Handler\FormErrorHandler(NULL, 'validators');
