<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vD8Uu7b' shared service.

return $this->privates['.service_locator.vD8Uu7b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Userconnecte' => ['privates', '.errored..service_locator.vD8Uu7b.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.vD8Uu7b": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repo' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'Userconnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'manager' => '?',
    'repo' => 'App\\Repository\\CompteRepository',
    'validator' => '?',
]);
