<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Ka755t\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Ka755t/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container5Ka755t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container5Ka755t\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container5Ka755t\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '5Ka755t',
    'container.build_id' => '71f5b9ec',
    'container.build_time' => 1564929100,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Ka755t');
