<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ4sqXRB\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ4sqXRB/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQ4sqXRB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQ4sqXRB\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerQ4sqXRB\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Q4sqXRB',
    'container.build_id' => '34b810d0',
    'container.build_time' => 1565779255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ4sqXRB');
