<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTVe70dv\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTVe70dv/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTVe70dv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTVe70dv\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerTVe70dv\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'TVe70dv',
    'container.build_id' => '6a7d64c8',
    'container.build_time' => 1564930307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTVe70dv');
