<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o8cnCb2' shared service.

return $this->privates['.service_locator.o8cnCb2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Userconnecte' => ['privates', '.errored..service_locator.o8cnCb2.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.o8cnCb2": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'repo' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
], [
    'Userconnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'repo' => 'App\\Repository\\ProfilRepository',
]);
