<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8ar7DhQ' shared service.

return $this->privates['.service_locator.8ar7DhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compte' => ['privates', '.errored..service_locator.8ar7DhQ.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.8ar7DhQ": it references class "App\\Entity\\Compte" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\UserCompteActuelRepository', 'getUserCompteActuelRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'userConnecte' => ['privates', '.errored..service_locator.8ar7DhQ.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.8ar7DhQ": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'compte' => 'App\\Entity\\Compte',
    'repo' => 'App\\Repository\\UserCompteActuelRepository',
    'serializer' => '?',
    'userConnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
