<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.59pZj8W' shared service.

return $this->privates['.service_locator.59pZj8W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repoCompte' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'repoDepot' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'userConnecte' => ['privates', '.errored..service_locator.59pZj8W.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.59pZj8W": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'repoCompte' => 'App\\Repository\\CompteRepository',
    'repoDepot' => 'App\\Repository\\DepotRepository',
    'serializer' => '?',
    'userConnecte' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
