<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjd0WsO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjd0WsO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGjd0WsO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGjd0WsO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGjd0WsO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gjd0WsO',
    'container.build_id' => '9efa9524',
    'container.build_time' => 1565279191,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjd0WsO');
