<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5rlqqRj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5rlqqRj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5rlqqRj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5rlqqRj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5rlqqRj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5rlqqRj',
    'container.build_id' => 'f75e20e0',
    'container.build_time' => 1565127687,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5rlqqRj');
