<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOUmQMfl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOUmQMfl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOUmQMfl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOUmQMfl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOUmQMfl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OUmQMfl',
    'container.build_id' => 'd2b65893',
    'container.build_time' => 1566856722,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOUmQMfl');
