<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.xml_deserialization_visitor' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Visitor/Factory/DeserializationVisitorFactory.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Visitor/Factory/XmlDeserializationVisitorFactory.php';

return $this->privates['jms_serializer.xml_deserialization_visitor'] = new \JMS\Serializer\Visitor\Factory\XmlDeserializationVisitorFactory();
