<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.metadata.xml_driver' shared service.

include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AbstractFileDriver.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Metadata/Driver/ExpressionMetadataTrait.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Metadata/Driver/XmlDriver.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedFileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocator.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Type/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Type/Parser.php';

return $this->privates['jms_serializer.metadata.xml_driver'] = new \JMS\Serializer\Metadata\Driver\XmlDriver(($this->privates['jms_serializer.metadata.file_locator'] ?? ($this->privates['jms_serializer.metadata.file_locator'] = new \Metadata\Driver\FileLocator([]))), ($this->privates['jms_serializer.serialized_name_annotation_strategy'] ?? $this->load('getJmsSerializer_SerializedNameAnnotationStrategyService.php')), ($this->privates['jms_serializer.type_parser'] ?? ($this->privates['jms_serializer.type_parser'] = new \JMS\Serializer\Type\Parser())));
